### ISSUE TITLE
关于头像绘制的样式

### ISSUE THREAD

**Issue by ShirasawaSama** [bs-community/blessing-skin-server#150]
# 关于头像绘制的样式

## 前言

个人感觉BlessingSkin的头像绘制有点不大好看, 现提供两种修改样式

## 样式1

![image](https://user-images.githubusercontent.com/17093811/76693686-6c8bea80-66a4-11ea-85ab-d176e79f0c98.png)

```css
.user-image {
  image-rendering: pixelated;
  border-radius: unset;
  box-shadow: unset;
  filter: drop-shadow(0 4px 4px rgba(0, 0, 0, .3));
}
```

### 兼容性: 
![image](https://user-images.githubusercontent.com/17093811/76693710-ea4ff600-66a4-11ea-8370-e4eb5e0844ea.png)

## 样式2

![image](https://user-images.githubusercontent.com/17093811/76693727-14091d00-66a5-11ea-9cc8-809573951e4c.png)

**这个样式需要后端绘制, 以下为前端css模拟**

```html
<div class="avatar"><img src="..."><img class="top" src="..."></div>
```

```less
.avatar {
  width: 80px;
  height: 80px;
  box-shadow: 0px 2px 4px -1px rgba(0, 0, 0, 0.2), 0px 4px 5px 0px rgba(0, 0, 0, 0.14), 0px 1px 10px 0px rgba(0, 0, 0, 0.12);

  img {
    display: block;
    width: 800%;
    margin: -100%;
    position: absolute;
    image-rendering: pixelated;
  }
  .top {
    margin-left: -500%;
    filter: drop-shadow(0px 2px 5px #0000005e) brightness(1.1);
  }
}
```

大概绘制过程就是:

1. 先绘制底层皮肤
2. 再绘制第二层皮肤
3. 给第二层皮肤加上一个向下偏移 `2px`, 对外扩展 `5px`, 颜色为 `#0000005e` 的投影
4. 修改第二层皮肤的亮度百分比为 `110%`
5. 同时由于这里头像比较大 *(80px)*, 因而还在绘制好的头像上再加了一层 `inset` 的投影 **(还是后端绘制)**

```css
.avatar::after {
  content: '';
  top: 0;
  position: absolute;
  width: 100%;
  height: 100%;
  box-shadow: inset 0px 0px 20px 0px #0000005e;
}
```

### 兼容性

![image](https://user-images.githubusercontent.com/17093811/76693799-38192e00-66a6-11ea-9b1e-d94c9453f31f.png)
