### ISSUE TITLE
Uncaught Error: Interface "SessionHandlerInterface" not found #530

### ISSUE THREAD

**Issue by sjempotje** [bs-community/blessing-skin-server#532]
### Which version of Blessing Skin are you using?

6.0.2

### Which version of PHP are you using?

8.1

### What browsers are you seeing the problem on?

Chrome

### Which web server are you using?

Nginx

### What happened?

An php error occured and I'm not sure how to solve this one.
Help is appreciated.

### Error Logs

```text
2023/01/21 21:29:28 [error] 19#19: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Interface "SessionHandlerInterface" not found in /home/container/webroot/vendor/laravel/framework/src/Illuminate/Session/FileSessionHandler.php:10

Stack trace:

#0 /home/container/webroot/vendor/composer/ClassLoader.php(571): include()

#1 /home/container/webroot/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()

#2 /home/container/webroot/vendor/laravel/framework/src/Illuminate/Session/SessionManager.php(73): Composer\Autoload\ClassLoader->loadClass()

#3 /home/container/webroot/vendor/laravel/framework/src/Illuminate/Session/SessionManager.php(61): Illuminate\Session\SessionManager->createNativeDriver()

#4 /home/container/webroot/vendor/laravel/framework/src/Illuminate/Support/Manager.php(105): Illuminate\Session\SessionManager->createFileDriver()

#5 /home/container/webroot/vendor/laravel/framework/src/Illuminate/Support/Manager.php(80): Illuminate\Support\Manager->createDriver()

#6 /home/container/webroot/vendor/laravel/framework/sr...PHP message: PHP Fatal error: Uncaught Error: Interface "SessionHandlerInterface" not found in /home/container/webroot/vendor/laravel/framework/src/Illuminate/Session/FileSessionHandler.php:10
```

### Steps to Reproduce

Using the https://blessing.netlify.app/en/setup.html steps and went to the website and I got the error.

**Comment by sjempotje** [comment]
Fixed it!

**Comment by 0AvA0** [comment]
Hello, I also encountered this problem, how can I solve it?

**Comment by sjempotje** [comment]
Hey, I use docker to host this and found the way I did was not configured correctly. I made this docker compose you can use:
```
version: "3.9"

services:
    web:
        image: php:8.0-apache
        ports:
            - "5080:80"
        volumes:
            - ./src:/var/www/html
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: yourpassword
            MYSQL_DATABASE: blessingskin
            MYSQL_USER: username
            MYSQL_PASSWORD: yourpassword
        ports:
            - "9906:3306"
```
in your terminal. make a folder in ur terminal location called src and put all the files there. then docker compose up and ur not really done. you still need to connect with the docker container to install the necessary extensions and change nginx location to public ofcourse! Hopes this helps. If not well that sucks.
